### ISSUE TITLE
【提问】如何获取直播间信息

### ISSUE THREAD

**Issue by Agnes4m** [wwweww/adapter-bilibili#6]
env配置项目以填写
```
DRIVER=~fastapi+~websockets
ROOM_ID_LIST=[114514] # 就是随机找一个测试，号码为直播间url：live.bilibili.com/最后的数字
login=true 
```
然后尝试在直播间输入几次弹幕，似乎没有任何响应
![image](https://github.com/wwweww/adapter-bilibili/assets/70925546/0dcdd456-9f36-46de-acf0-6d8e4293911d)

**Comment by Agnes4m** [comment]
换了一个热门且有大量弹幕的直播间测试，发现只能获取到部分消息事件，但是无法获取弹幕信息以及sc留言。个人猜想b站今年多次更换直播间api，导致了原本的api是不可用状态，因此无法正确获取弹幕信息。

由于无法获取事件信息，因此也无法通过nb进行处理，更无法进行回复
![image](https://github.com/wwweww/adapter-bilibili/assets/70925546/1cf0d713-e46f-45c9-92e3-29b6c0dde27b)

**Comment by wwweww** [comment]
好像是这样  我看看修补一下 谢谢提醒！
